AuMVC/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuMVC.Data;
using AuMVC.Data.Models;
using AuMVC.Data.Services;
using AuMVC.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AuMVC.Controllers
{
    public class IssueController : Controller
    {
        private IIssueService _issueService;
        private ISiteService _siteService;

        public IssueController(IIssueService issueService, ISiteService siteService)
        {
            _issueService = issueService;
            _siteService = siteService;
        }


        //all issues--
        public ActionResult IndexIssue()
        {
            List<Issue> issues = _issueService.allIssues();
            return View(issues);
        }







        // GET: Issue

        public ActionResult CreateIssue()
        {
            IssueViewModel issueVM = new IssueViewModel()
            {
                Sites = _siteService.allSites()
            };

            return View(issueVM);
        }

        [HttpPost]
        public ActionResult CreateIssue(IssueViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "IssueProblem");

                return View();
                //Redirect tek nje error page
            }


            _issueService.CreateIssue(viewModel);

            return View(new IssueViewModel(){ Sites = _siteService.allSites() });
        }








        //edit issue

        public ActionResult EditIssue(int id)
        {
            Issue myIssue = _issueService.GetIssueById(id);
            return View(myIssue);
        }

        
        public ActionResult EditConfirm(Issue issue)
        {
            _issueService.UpdateIssue(issue);
            return View();

        }



        //deleteissue

        public ActionResult DeleteIssue(int id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }


            if (!_issueService.Exists(id))
            {
                return RedirectToAction("Index");
            }
            return View(_issueService.GetIssueById(id));
        }


        // POST: Issue/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmIssue(int id)
        {
            _issueService.Delete(id);
            return RedirectToAction("IndexIssue");
        }
    }
}

AuMVC/Controllers/MaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuMVC.Data;
using AuMVC.Data.Models;
using AuMVC.Data.Services;
using AuMVC.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AuMVC.Controllers
{
    public class MaintenanceController : Controller
    {


        private IMaintenanceService _maintenanceService;
        private ISiteService _siteService;
        public MaintenanceController(IMaintenanceService maintenanceService, ISiteService siteService)
        {
            _maintenanceService = maintenanceService;
            _siteService = siteService;
        }



        //all maintenances--
        
        public ActionResult IndexMaintenance()
        {
            List<Maintenance> maintenances = _maintenanceService.allMaintenances();
            return View(maintenances);
        }





        // GET: Maintenance
        public ActionResult CreateMaintenance()
        {
            MaintenanceViewModel maintenanceVM = new MaintenanceViewModel()
            {
                Sites = _siteService.allSites()
            };
            return View(maintenanceVM);
        }

        [HttpPost]
        public ActionResult CreateMaintenance(MaintenanceViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "MaintenanceProblem");

                return View();
                //Redirect tek nje error page
            }
            

            _maintenanceService.CreateMaintenance(viewModel);
            return View(new MaintenanceViewModel() { Sites = _siteService.allSites() });
        }






        //editmaintenance
        public ActionResult EditMaintenance(int id)
        {
            Maintenance myMaintenance = _maintenanceService.GetMaintenanceById(id);
                return View(myMaintenance);
        }

        public ActionResult EditConfirm(Maintenance maintenance)
        {

            _maintenanceService.UpdateMaintenance(maintenance);
            return View();
        }






        //delete maintenance
        public ActionResult DeleteMaintenance(int id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            
            if (!_maintenanceService.Exists(id))
            {
                return RedirectToAction("Index");
            }
            return View(_maintenanceService.GetMaintenanceById(id));
        }



        // POST: Maintenance/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmMaintenance(int id)
        {
            _maintenanceService.Delete(id);
            return RedirectToAction("IndexMaintenance");
        }
    }
}

AuMVC/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AuMVC.Data;
using AuMVC.Data.Models;
using AuMVC.Data.Services;
using AuMVC.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AuMVC.Controllers
{
    public class SiteController : Controller
    {
        private ISiteService _siteService;

        public SiteController(ISiteService siteService)
        {
            _siteService = siteService;
        }

        // GET: All Sites
        public ActionResult Index()
        {
            List<Site> sites = _siteService.allSites();
            return View(sites);
        }

        public ActionResult CreateSite()
        {
            return View("~/Views/Site/Create.cshtml", new SiteViewModel());
        }


        //[HttpPost]

        public ActionResult Create(SiteViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Site Problem");
                return View();
            }

            _siteService.CreateSite(viewModel);
            return View();
        }

        public ActionResult Edit(int id)
        {
            Site mySite = _siteService.GetSiteById(id);
            return View(mySite);
        }

        [ValidateAntiForgeryToken]
        public ActionResult EditConfirm(Site site)
        {
            _siteService.UpdateSite(site);
            return View();
        }

        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            if (!_siteService.Exists(id))
            {
                return RedirectToAction("Index");
            }
            return View(_siteService.GetSiteById(id));
        }



        // POST: Site/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            _siteService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

AuMVC/Controllers/VariationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuMVC.Data;
using AuMVC.Data.Models;
using AuMVC.Data.Services;
using AuMVC.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AuMVC.Controllers
{
    public class VariationController : Controller
    {

        private IVariationService _variationService;
        private ISiteService _siteService;

        public VariationController(IVariationService variationService, ISiteService siteService)
        {
            _variationService = variationService;
            _siteService = siteService;
        }



        //all variations--
        public ActionResult IndexVariation()
        {
            List<Variation> variation = _variationService.allVariations();
            return View(variation);
        }



        // GET: Variation
        public ActionResult CreateVariation()
        {
            VariationViewModel variatonVM = new VariationViewModel()
            {
                Sites = _siteService.allSites()
            };

            return View(variatonVM);
        }

        [HttpPost]
        public ActionResult CreateVariation(VariationViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "VariationProblem");

                return View();
                //Redirect tek nje error page
            }
            _variationService.CreateVariation(viewModel);

            return View(new VariationViewModel() { Sites = _siteService.allSites() });

        }



        //editvariation
        public ActionResult EditVariation(int id)
        {
            
                Variation myVariation = _variationService.GetVariationById(id);
                return View(myVariation);
            
        }

        public ActionResult EditConfirm(Variation variation)
        {

            _variationService.UpdateVariation(variation);
            return View();
        }




        //delete variation
        public ActionResult DeleteVariation(int id)
        {
            if (id == null)
            {
                return RedirectToAction("IndexVariation");
            }
            
            if (!_variationService.Exists(id))
            {
                return RedirectToAction("IndexVariation");
            }
            return View(_variationService.GetVariationById(id));
        }



        // POST: variation/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmVariation(int id)
        {
            _variationService.Delete(id);
            return RedirectToAction("IndexVariation");
        }

    }
}
    

AuMVC/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

AuMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  AuMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AuMVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Site" asp-action="Index">Sites</a></li>
                    <li><a asp-area="" asp-controller="Issue" asp-action="IndexIssue">Issues</a></li>
                    <li><a asp-area="" asp-controller="Maintenance" asp-action="IndexMaintenance">Maintenance</a></li>
                    <li><a asp-area="" asp-controller="ProgressStage" asp-action="IndexProgressStage">Progress Stage</a></li>
                    <li><a asp-area="" asp-controller="Variation" asp-action="IndexVariation">Variation</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    @await Html.PartialAsync("LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Enian Tafa</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>