AuMVC/Controllers/ProgressStageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuMVC.Data;
using AuMVC.Data.Models;
using AuMVC.Data.Services;
using AuMVC.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AuMVC.Controllers
{
    public class ProgressStageController : Controller
    {

        private IProgressStageService _progressStageService;
        private ISiteService _siteService;

        public ProgressStageController(IProgressStageService progressStageService, ISiteService siteService)
        {
            _progressStageService = progressStageService;
            _siteService = siteService;

        }


        //all prog stages--
        public ActionResult IndexProgressStage()
        {
            List<ProgressStage> progressStage = _progressStageService.allProgressStages();
            return View(progressStage);
        }






        // GET: ProgressStage
        public ActionResult CreateProgressStage()
        {
            ProgressStageViewModel progressStageVM = new ProgressStageViewModel()
            {
                Sites = _siteService.allSites()
            };

            return View(progressStageVM);
        }


        [HttpPost]
        public ActionResult CreateProgressStage(ProgressStageViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "ProgressStageProblem");

                return View();
                //Redirect tek nje error page
            }



            _progressStageService.CreateProgressStage(viewModel);

            return View(new ProgressStageViewModel() { Sites = _siteService.allSites() });
        }




        //edit


        public ActionResult EditProgressStage(int id)
        {

            ProgressStage myProgressStage = _progressStageService.GetProgressStageById(id);
            return View(myProgressStage);

        }

       
        public ActionResult EditConfirm(ProgressStage progressStage)
        {
            _progressStageService.UpdateProgressStage(progressStage);
            return View();

        }








        //delete progstage
        public ActionResult DeleteProgressStage(int id)
        {
            if (id == null)
            {
                return RedirectToAction("IndexProgressStage");
            }

            if (!_progressStageService.Exists(id))
            {
                return RedirectToAction("IndexProgressStage");
            }
             return View(_progressStageService.GetProgressStageById(id));
        }



        // POST: Progstage/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmProgressStage(int id)
        {
             _progressStageService.Delete(id);
            return RedirectToAction("IndexProgressStage");
        }

    } }

AuMVC/Views/ProgressStage/CreateProgressStage.cshtml
@using AuMVC.Data.Enums;
@model AuMVC.Data.ViewModels.ProgressStageViewModel
@{
    ViewBag.Title = "Create Progress Stage";
}

<h2>CreateProgressStage</h2>


@using (Html.BeginForm("CreateProgressStage", "ProgressStage", FormMethod.Post))
{
    <p class="alert alert-info"> All fields are <strong>Required</strong></p>

    <form>
        <div class="form-group">
            <label>Site Number</label>
            @Html.DropDownListFor(m => m.SiteId, new SelectList(Model.Sites.Select(x => new { Value = x.Id, Text = x.SiteNumber }), "Value", "Text"),
                             "Select a site",
                             htmlAttributes: new { @class = "form-control border-input" })
            @Html.ValidationMessageFor(model => model.SiteId, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Stage)

            @Html.DropDownListFor(model=>model.Stage,
         Html.GetEnumSelectList<ProgressStageStage>(),
         "ProgressStageStage", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Stage, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Value)
            @Html.TextBoxFor(m => m.Value, new { @class = "form-control", placeholder = "Enter the Value" })
            @Html.ValidationMessageFor(m => m.Value, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateCompleted)
            @Html.TextBoxFor(m => m.DateCompleted, new { @class = "form-control", @type = "date" })
            @Html.ValidationMessageFor(m => m.DateCompleted, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CompletedBy)
            @Html.TextBoxFor(m => m.CompletedBy, new { @class = "form-control", placeholder = "Name/Surname" })
            @Html.ValidationMessageFor(m => m.CompletedBy, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateApproved)
            @Html.TextBoxFor(m => m.DateApproved, new { @class = "form-control", @type = "date" })
            @Html.ValidationMessageFor(m => m.DateApproved, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ApprovedBy)
            @Html.TextBoxFor(m => m.ApprovedBy, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ApprovedBy, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.PaymentStatus)

            @Html.DropDownListFor(model=>model.PaymentStatus,
         Html.GetEnumSelectList<ProgressStagePaymentStatus>(),
         "ProgressStagePaymentStatus", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PaymentStatus, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.DatePaid)
            @Html.TextBoxFor(m => m.DatePaid, new { @class = "form-control", @type = "date" })
            @Html.ValidationMessageFor(m => m.DatePaid, "", new { @class = "text-danger" })
        </div>


        <button type="submit" class="btn btn-primary">Save</button>
    </form>

}

AuMVC/Views/ProgressStage/DeleteProgressStage.cshtml
@model AuMVC.Data.Models.ProgressStage
@{
    ViewBag.Title = "Delete Progress Stage";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProgressStage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(m => m.Stage)
        </dt>
        <dd>
            @Html.DisplayFor(m => m.Value)
        </dd>
        <dt>
            @Html.DisplayNameFor(m => m.DateCompleted)
        </dt>
        <dd>
            @Html.DisplayFor(m => m.DateApproved)
        </dd>
        <dt>
            @Html.DisplayNameFor(m => m.ApprovedBy)
        </dt>
        <dd>
            @Html.DisplayFor(m => m.PaymentStatus)
        </dd>
        <dt>
            @Html.DisplayNameFor(m => m.DatePaid)
        </dt>

    </dl>

    @using (Html.BeginForm("DeleteConfirmProgressStage", "ProgressStage", FormMethod.Post))
    {

        @Html.HiddenFor(n => n.Id);

        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            |
            @Html.ActionLink("Back to List", "IndexProgressStage")
        </div>
    }
</div>

AuMVC/Views/ProgressStage/EditConfirm.cshtml
@{
    ViewData["Title"] = "EditConfirm";
}

<h2>Changes were saved</h2>

AuMVC/Views/ProgressStage/EditProgressStage.cshtml
@using AuMVC.Data.Enums;
@model AuMVC.Data.Models.ProgressStage
@{
    ViewData["Title"] = "Edit Progress Stage";
}

<h2>EditProgressStage</h2>



@using (Html.BeginForm("EditConfirm", "ProgressStage", FormMethod.Post))
{


<form>
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Stage)

        @Html.DropDownListFor(model => model.Stage,
            Html.GetEnumSelectList<ProgressStageStage>(),
            "ProgressStageStage", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Stage, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Value)
        @Html.TextBoxFor(m => m.Value, new { @class = "form-control", placeholder = "Enter the Value" })
        @Html.ValidationMessageFor(m => m.Value, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DateCompleted)
        @Html.TextBoxFor(m => m.DateCompleted, new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(m => m.DateCompleted, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.CompletedBy)
        @Html.TextBoxFor(m => m.CompletedBy, new { @class = "form-control", placeholder = "Name/Surname" })
        @Html.ValidationMessageFor(m => m.CompletedBy, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DateApproved)
        @Html.TextBoxFor(m => m.DateApproved, new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(m => m.DateApproved, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ApprovedBy)
        @Html.TextBoxFor(m => m.ApprovedBy, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ApprovedBy, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PaymentStatus)

        @Html.DropDownListFor(model => model.PaymentStatus,
       Html.GetEnumSelectList<ProgressStagePaymentStatus>(),
       "ProgressStagePaymentStatus", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.PaymentStatus, "", new { @class = "text-danger" })
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.DatePaid)
        @Html.TextBoxFor(m => m.DatePaid, new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(m => m.DatePaid, "", new { @class = "text-danger" })
    </div>


    <button type="submit" class="btn btn-primary">Save</button>
</form>

}

AuMVC/Views/ProgressStage/IndexProgressStage.cshtml
@using AuMVC.Data.Models
@model List<ProgressStage>

@{
    ViewData["Title"] = "Progress Stage";
}


<button type="button" class="btn btn-default"> @Html.ActionLink("Add New", "CreateProgressStage", "ProgressStage" ) </button>

@if (Model.Any())
{
    <table class="table table-striped">
        <thead>
            <tr class="info">
                <td>Stage</td>
                <td>Value</td>
                <td>Date Completes</td>
                <td>Completed By</td>
                <td>Date Approved</td>
                <td>Approved by</td>
                <td>Payment Status</td>
                <td>Date Paid</td>

            </tr>

        </thead>

        <tbody>
            @foreach (ProgressStage progressStage in Model)
            {
                <tr>
                    <td>@progressStage.Stage</td>
                    <td>@progressStage.Value</td>
                    <td>@progressStage.DateCompleted</td>
                    <td>@progressStage.DateApproved</td>
                    <td>@progressStage.ApprovedBy</td>
                    <td>@progressStage.PaymentStatus</td>
                    <td>@progressStage.DatePaid</td>

                    <td type="button" class="btn btn-default">@Html.ActionLink("Edit", "EditProgressStage", "ProgressStage", new { @id = progressStage.Id })</td>
                    <td type="button" class="btn btn-default">@Html.ActionLink("Delete", "DeleteProgressStage", "ProgressStage", new { @id = progressStage.Id })</td>
                </tr>
            }
        </tbody>
    </table>

}


else
{
    <h1 class="text-center text-danger">There are no Progress Stage yet!</h1>

}